name: Run RSpec

on:
  workflow_dispatch:
    inputs:
      rubyVersion:
        description: 'Ruby Version'
        required: true
        default: '2.4' 
        type: choice
        options:
        - '2.4'
        - '2.7'
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  RUBY_VERSION: ${{ github.event.inputs.rubyVersion || '2.4' }}

jobs:
  test:
    runs-on: ubuntu-latest
    # PR が Draft である or PR タイトルに "[skip ci]" が含まれている場合は実行スキップする
    if: ${{ !github.event.pull_request.draft && !contains(github.event.pull_request.title, '[skip ci]')}}
    steps:
      - name: Dump context
        run: echo '${{ toJSON(github) }}'
      - name: Ruby v2.4
        if: ${{ env.RUBY_VERSION == '2.4' }}
        run: echo 'Exec 2.4'
      - name: Ruby v2.7
        if: ${{ env.RUBY_VERSION == '2.7' }}
        run: echo 'Exec 2.7'
      # Slack通知
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Test Success
          SLACK_MESSAGE: Ruby v${{ env.RUBY_VERSION }}
          SLACK_COLOR: good
          MSG_MINIMAL: true
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Test Failure
          SLACK_MESSAGE: Ruby v${{ env.RUBY_VERSION }}
          SLACK_COLOR: danger