name: Run RSpec

on:
  workflow_dispatch:
    inputs:
      rubyVersion:
        description: 'Ruby Version'
        required: true
        default: '2.4' 
        type: choice
        options:
        - '2.4'
        - '2.7'
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'
      - run: |
          echo "Ruby Version: $VERSION"
        env:
          VERSION: ${{ github.event.inputs.rubyVersion }}
      - name: Rub Ruby v2.4
        if: ${{ github.event.inputs.rubyVersion == '2.4' }}
        run: echo 'Exec 2.4'
      - name: Rub Ruby v2.7
        if: ${{ github.event.inputs.rubyVersion == '2.7' }}
        run: echo 'Exec 2.7'