name: Run RSpec

on:
  workflow_dispatch:
    inputs:
      rubyVersion:
        description: 'Ruby Version'
        required: true
        default: '2.4' 
        type: choice
        options:
        - '2.4'
        - '2.7'
  pull_request:
    types: [opened, edited]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        run: echo '${{ toJSON(github) }}'
      - name: Ruby v2.4
        if: ${{ github.event.inputs.rubyVersion == '2.4' }}
        run: echo 'Exec 2.4'
      - name: Ruby v2.7
        if: ${{ github.event.inputs.rubyVersion == '2.7' }}
        run: echo 'Exec 2.7'
      # Slack通知
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Test Success
          SLACK_MESSAGE: Ruby v${{ github.event.inputs.rubyVersion }}
          SLACK_COLOR: good
          MSG_MINIMAL: true
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Test Failure
          SLACK_MESSAGE: Ruby v${{ github.event.inputs.rubyVersion }}
          SLACK_COLOR: danger